GET http://localhost:3000/TipoCarga

###POST 
POST http://localhost:3000/TipoCarga/
Content-Type: application/json

{
  "nombre": "Muebles",
  "descripcion": "Pesado"
}

###Actualizar 
PUT http://localhost:3000/TipoCarga/6860b8996bd3d09a98c60682
Content-Type: application/json

{
  "nombre": "Saphiro",
  "descripcion": "Extremadaente lujoso"
}

###Remove
DELETE http://localhost:3000/TipoCarga/6860b8996bd3d09a98c60682

###Fin Onde
GET http://localhost:3000/TipoCarga/6860757ac8dad72bd03244ce